version: 2
updates:

  - package-ecosystem: "composer"
    directory: "/"
    commit-message:
      prefix: "dep"
    schedule:
      interval: "monthly"
    pull-request-branch-name:
      separator: "-"
    groups:
      prod:
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"
      dev:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    commit-message:
      prefix: "dep"
    schedule:
      interval: "monthly"
    pull-request-branch-name:
      separator: "-"
    groups:
      prod:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "docker"
    directory: "/docker/sakoo.app"
    commit-message:
      prefix: "dep"
    schedule:
      interval: "monthly"
    pull-request-branch-name:
      separator: "-"
    groups:
      prod:
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"
      dev:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"