name: CI Pipeline

on:
  push:
    branches: 
      - '**'

  pull_request:
    branches:
      - '**'

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    # - name: Dependency Review
    #   uses: actions/dependency-review-action@v3

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --ignore-platform-reqs


    - name: Test1
      run: docker-compose up -d

    - name: Test1
      run: make test
    # - name: Build docker image dev
    #   run: docker build . -f ./docker/sakoo.app/Dockerfile -t sakoo.app -q

    # - name: Build docker image prod
    #   run: docker build . -f ./docker/sakoo.app/Dockerfile.prod -t sakoo-prod.app -q

    # - name: Code style check
    #   run: docker run -v $PWD:/var/www/html/ sakoo.app composer stylecheck

    # - name: Run automated tests dev
    #   run: docker run -v $PWD:/var/www/html/ sakoo.app composer test

    # - name: Run automated tests prod
    #   run: docker run sakoo-prod.app composer test